#
# Travis CI recipe to build docker image.
#

sudo: required

language: generic

services:
  - docker

script:
  - echo "Starting build of Docker image..."
  - docker build --no-cache --pull -t $TRAVIS_REPO_SLUG:$TRAVIS_JOB_ID .
